from typing import Any, Dict, List, Tuple

def decode(data: str) -> Any: ...

class Message:
    jsonrpc: str
    id: str
    method: str
    params: Tuple[List[Any], Dict[str, Any]]

    def __init__(self, kw: bool = True) -> None: ...
    def __repr__(self) -> str: ...
    def set_param(self, name: str, value: str) -> None: ...
